### ISSUE TITLE
UI station selection interferes with the system-wide audio controls

### ISSUE THREAD

**Issue by otede** [dend/beem#14]
This one will be rather vague. I'll provide more info if I stumble upon it again.

Basically if channels are selected in the app UI (I don't know whether through thumbnails or the fwd/rew controls) and via the system-wide audio controls at some point switching from another app to Beem will not present the currently playing channel but instead switch to another channel.

Which gets overriden by which - I don't know, sorry.

WP 7.8 and WP 8, latest as of July 2013.

**Comment by dend** [comment]
Product is no longer supported. Closing issue.
