### ISSUE TITLE
Play the buffered content until new content is ready for playback

### ISSUE THREAD

**Issue by otede** [dend/beem#20]
I think the title is rather self explanatory. Correct me if I'm wrong but IIRC such behavior was present in older Beem versions, 1.6.x particularly.

Currently playback is interrupted immediatelly a new station is selected. Combined with all the other issues that interrupt playback it makes for a poor experience.

WP 7.8 and WP 8, latest as of July 2013

**Comment by dend** [comment]
Product is no longer supported. Closing issue.
