### ISSUE TITLE
GitHub Integration

### ISSUE THREAD

**Issue by Racxie** [dend/beem#24]
This would be a more practical way for people to provide bug reports/app ideas rather than e-mailing you directly (like I did). Here's a suggestion of a way you could go about this:

On the 'about' page have a button that says something along the lines of "submit bug/idea" which takes you to another page with a short description explaining why you use GitHub (e.g. easier to keep track of progress and for others to see if a bug has already been submitted), and having two buttons below for registering and login in. Here's an example:

![githubexample](https://f.cloud.github.com/assets/5277392/1000756/1f6cdb9e-0a56-11e3-9ab5-5fc6acb14289.jpg)

The register button could have a form to fill in which then fills the information in the background on the site, or take you to the register page via IE, while the login could  take you straight to the issues page (or the browser could be within the app?).

The login could also save your credentials so that if the user ever needs to login to GitHub again, the app could do it for them.

**Comment by dend** [comment]
After a close assessment of the issue, I decided that for now this is not the right experience and I would avoid adding application bloat.

I will rely on email feedback and focus on delivering a delightful music experience.
