### ISSUE TITLE
Pushed to background (PtB) - soft-crashes when task-switched

### ISSUE THREAD

**Issue by otede** [dend/beem#42]
Video available: yes
1. start Beem
2. start station
3. browse some heavy websites untill Beem is pushed far back in the task switcher; this is what I call PtB
4. task-switch to Beem
5. Beem soft-crashes (see the screenshots https://onedrive.live.com/redir?resid=66CF2646234394FC!4990&authkey=!AFD65MJdjVgVLKs&ithint=folder%2c.png)

Soft-crashed Beem can still play music (via system-wide controls). Consequentyl clicking on the title on the system-wide controls will effectively restart the app with the station visible and playing.
I'm reporting it against 2.x but this dates way back to, IIRC, 1.8. IIRC it was even reproducible with 1.8+L900+WP7(?).

Beem with DI.fm premium
Phone:
HTC 8X
HTC 8S
Firmware and OS version:
All during the last 12 months / since the release of Beem 2.x
(I don't recall a slightest change during that time with regard to the bugs I'm reporting this month)
Up to and including the recent WP 8.1 Preview for Developers (my current system)

**Comment by dend** [comment]
Product is no longer supported. Closing issue.
