### ISSUE TITLE
Playback stalls few times or for good

### ISSUE THREAD

**Issue by otede** [dend/beem#43]
Video available: yes

More often than not it goes like this:
1. start Beem
2. start a new station
3. station starts playing
4. after a ~second or so it pauses for ~3 seconds
5. it pauses again and resumes
6a. playback starts normally, usually without further stalls
6b. playback stalls for good with the station screen displayed normally; see #45 

Variants:
6a - my home wifi (fast)
6b - my work wifi (slow-ish, ~4Mbps)

Note1: This never _ever_ happens on the official DI.fm app, even with premium 256 kbps stream
Note2: The play/pause icon blinks each time the playback stalls/resumes.

**Comment by dend** [comment]
Product is no longer supported. Closing issue.
