### ISSUE TITLE
Unpaused buffered content plays then station stalls for good

### ISSUE THREAD

**Issue by otede** [dend/beem#44]
1. start Beem
2. start station
3. pause station and lock screen
4. leave for 10+ minutes
5. unlock screen and unpause station
6. buffered content plays then then station stalls for good; see #45 

Beem with DI.fm premium
Phone:
HTC 8X
HTC 8S

Firmware and OS version:
All during the last 12 months / since the release of Beem 2.x
(I don't recall a slightest change during that time with regard to the bugs I'm reporting this month)
Up to and including the recent WP 8.1 Preview for Developers (my current system)

**Comment by dend** [comment]
Product is no longer supported. Closing issue.
