### ISSUE TITLE
Can't start station after playback stalls

### ISSUE THREAD

**Issue by otede** [dend/beem#45]
1. playback stalls for good on the desired station (see #43, variant 6b)
2. backx1 to favorites
3. app blinks the desired station and throws me back into favorites each time I try
   This won't change until I:
   1w. start some other station (adjacent to the desired station for convenience)
   2w. use the PREV / NEXT station buttons to navigate to the desired station
   OR
   3w. click the 'Play' button on the system-wide audio controls.

Beem with DI.fm premium
Phone:
HTC 8X
HTC 8S

Firmware and OS version:
All during the last 12 months / since the release of Beem 2.x
(I don't recall a slightest change during that time with regard to the bugs I'm reporting this month)
Up to and including the recent WP 8.1 Preview for Developers (my current system)

**Comment by dend** [comment]
Product is no longer supported. Closing issue.
