### ISSUE TITLE
Task-switching reloads or unpauses a station

### ISSUE THREAD

**Issue by otede** [dend/beem#47]
Video available: yes
1. start Beem
2. start station
3. browse some light websites or start an app like Evernote
4. task-switch to Beem
5. Beem reloads the currently playing station or unpauses it if the station was paused

Note: Beem also unpauses station after finishing a phone call (after call has been answered with station playback on at the time).

Beem with DI.fm premium
Phone:
HTC 8X
HTC 8S

Firmware and OS version:
All during the last 12 months / since the release of Beem 2.x
(I don't recall a slightest change during that time with regard to the bugs I'm reporting this month)
Up to and including the recent WP 8.1 Preview for Developers (my current system)

**Comment by dend** [comment]
Product is no longer supported. Closing issue.
