### ISSUE TITLE
Favorites sorted by time added instead of alphabetically

### ISSUE THREAD

**Issue by otede** [dend/beem#49]
Beem with DI.fm premium
Phone:
HTC 8X
HTC 8S

Firmware and OS version:
All during the last 12 months / since the release of Beem 2.x
(I don't recall a slightest change during that time with regard to the bugs I'm reporting this month)
Up to and including the recent WP 8.1 Preview for Developers (my current system)

**Comment by dend** [comment]
Product is no longer supported. Closing issue.
