### ISSUE TITLE
[req] Add an option to sort recorded by time

### ISSUE THREAD

**Issue by otede** [dend/beem#56]
It has been raised here https://github.com/dend/beem/issues/12 but I'd like to ask again in a separate topic. To sum up my arguments pro introduction of such feature:
Even if a person know a significant number of artist names of the channels he listens to on DI (highly unlikely IMO) the scenario [let's check that 3 tunes I've recently recorded] is far more likely to occur than [let's check the tunes of the <specific artist> I've recorded].

On top of that... pretty please! :)

**Comment by dend** [comment]
Closing this one because it's a lower-priority item and it would add complexity to the simple experience.
