### ISSUE TITLE
New stations not added.

### ISSUE THREAD

**Issue by otede** [dend/beem#57]
Some new ones Are missing e.g. Old-school rave and few more.

**Comment by otede** [comment]
Is the project dead?

**Comment by dend** [comment]
Nope. Absolutely not. Actually waiting to push the new update with new stations and functionality within the next month.

**Comment by dend** [comment]
Marking this as urgent for follow-up. Stations need to be added within this week.

**Comment by otede** [comment]
Waiting for Windows 10 release? ;)

**Comment by dend** [comment]
Nope, hope to get that in this weekend for the old client.

**Comment by otede** [comment]
Some stations already listed won't work anymore (00..., Chip Tunes...). Your app is neglected and falls apart ;)

**Comment by otede** [comment]
The Chip Tunes channel has actually been removed by DI.fm but the issue still applies to other stations. There were like 10 new stations added since the Beem was last updated.

**Comment by thezoggy** [comment]
any chance of getting the stations updated? wife has been asking daily when `Indie Dance` will show up

**Comment by dend** [comment]
Working on those today!

**Comment by otede** [comment]
Damn, don't mind the stations, I was starting to worry something has happened to you :)

Sent from my Windows Phone
________________________________

**Comment by dend** [comment]
Not at all, but you know - full time responsibilities and all :-)

**Comment by dend** [comment]
Product is no longer supported. Closing issue.
