### ISSUE TITLE
dead project?

### ISSUE THREAD

**Issue by thezoggy** [dend/beem#59]
this project appears to have died off.. any chance of making your azure data available so others can update/maintain it?

**Comment by dend** [comment]
Not died off just yet. Funnily enough I have a new build sitting at home, just need to migrate some of the APIs before I release it - don't want to constantly update the Azure table when a new station comes up. Stay tuned.

**Comment by otede** [comment]
Please release the beta as-is or anything. The di support told me they met a bum the other day and he convinced them "windows phone is dead" so their app is effectively an abandonware.

**Comment by dend** [comment]
@otede yikes. Will need to revise the DI.FM API and see what changed. Now that I can build this as a UWP app that will run both on Windows and Windows Phone.

**Comment by otede** [comment]
What has changed? To me the voice message I get in Beem Is clear. They have disallowed any third-party apps.

**Comment by dend** [comment]
>  They have disallowed any third-party apps.
Source on this statement?

**Comment by otede** [comment]
Launch Beem
play any channel, premium or not
hear a guy saying that due to licensing only the official client and the web player are allowed to be used (looped)

**Comment by dend** [comment]
@otede Gotcha. Will have to look into that. I believe they might've introduced custom content licensing and DRM (no idea if that is the case until I actually look at the streams). If that is the case, then it's pretty much game over for Beem.

**Comment by dend** [comment]
Product is no longer supported. Closing issue.
