### ISSUE TITLE
Recorded song is lost when screen times out

### ISSUE THREAD

**Issue by otede** [dend/beem#9]
1. Enable recording.
2. Wait for the screen to time out.
3. Unlock the phone.
   Actual result:
   The recording is lost.

Expected result:
The recording is preserved. After unlocking the phone the app greets with the usual recording name dialogue. A note: Before 1.8 screen time out would not cause recorded file loss. 

WP 7.8 and WP 8, latest as of July 2013.

**Comment by dend** [comment]
Product is no longer supported. Closing issue.
